FROM alexeldeib/bpftrace-bin-xenial-llvm-8:2020-01-27T07-00-00

RUN apt install -y python3 python3-pip python3-virtualenv 

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m virtualenv --python=/usr/bin/python3 ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"
RUN pip install --upgrade pip setuptools
RUN pip install magic-wormhole

RUN apt install -y locales 
RUN locale-gen en_US.UTF-8

RUN apt install -y git
RUN git clone https://github.com/brendangregg/FlameGraph
