name: build images

on:
    push:
        branches:
            - master
    schedule:
        - cron: "0 4 * * *"

env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    REPO: docker.io/alexeldeib
    IMG_PREFIX: bpftrace-

jobs:
    bpftrace:
        runs-on: ubuntu-16.04
        strategy:
          matrix:
            llvm: [8]
            distro: [xenial]
        steps:
            - uses: actions/checkout@master
            - name: build image
              run: |
                set -eux
                docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
                TAG=$(date -Ihours | tr :+ -)
                echo "TAG: ${TAG}"
                docker build --build-arg distro=${{ matrix.distro }} --build-arg LLVM_VERSION=${{ matrix.llvm }} -t ${REPO}/${IMG_PREFIX}${{ matrix.distro }}-llvm-${{ matrix.llvm }}:${TAG} .
                docker build -f Dockerfile.final --build-arg IMG=${REPO}/${IMG_PREFIX}${{ matrix.distro }}-llvm-${{ matrix.llvm }} --build-arg TAG=${TAG} -t ${REPO}/${IMG_PREFIX}bin-${{ matrix.distro }}-llvm-${{ matrix.llvm }}:${TAG} .
                docker push ${REPO}/${IMG_PREFIX}${{ matrix.distro }}-llvm-${{ matrix.llvm }}:${TAG}
                docker tag ${REPO}/${IMG_PREFIX}${{ matrix.distro }}-llvm-${{ matrix.llvm }}:${TAG} ${REPO}/${IMG_PREFIX}${{ matrix.distro }}-llvm-${{ matrix.llvm }}:latest
                docker push ${REPO}/${IMG_PREFIX}bin-${{ matrix.distro }}-llvm-${{ matrix.llvm }}:${TAG}
                docker tag ${REPO}/${IMG_PREFIX}bin-${{ matrix.distro }}-llvm-${{ matrix.llvm }}:${TAG} ${REPO}/${IMG_PREFIX}bin-${{ matrix.distro }}-llvm-${{ matrix.llvm }}:latest
                docker push ${REPO}/${IMG_PREFIX}bin-${{ matrix.distro }}-llvm-${{ matrix.llvm }}:${TAG}
                docker run -t --rm -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} ${REPO}/${IMG_PREFIX}${{ matrix.distro }}-llvm-${{ matrix.llvm }}:${TAG} cp /usr/local/bin/bpftrace ${GITHUB_WORKSPACE}/bpftrace-${{ matrix.distro }}-llvm-${{ matrix.llvm }}
            - uses: actions/upload-artifact@v1
              with:
                name: bpftrace-${{ matrix.distro }}-llvm-${{ matrix.llvm }}
                path: bpftrace-${{ matrix.distro }}-llvm-${{ matrix.llvm }}